// vue-lynx-ui/src/components/button/Button.vue
<!--
  Copyright 2026 The Lynx Authors. All rights reserved.
  Licensed under the Apache License Version 2.0 that can be found in the
  LICENSE file in the root directory of this source tree.

  Vue Lynx port of the ReactLynx `<Button>` headless component.
  The public API mirrors `packages/lynx-ui-button/src/Button.tsx` 1:1:
    - props:  disabled, className, style, buttonProps
    - emits:  click                (React: onClick)
    - slot:   default scoped slot  (React: render-prop children)
    - context: { active, disabled } provided to descendants
    - injects `ui-active` / `ui-disabled` state classes for CSS styling
-->
<script setup lang="ts">
import { computed } from 'vue-lynx'

import { provideButtonContext } from './context.js'
import { useTouchActive } from './useTouchActive.js'
import type { ButtonEmits, ButtonProps } from './types.js'

const props = withDefaults(defineProps<ButtonProps>(), {
  disabled: false,
})

const emit = defineEmits<ButtonEmits>()

// Reactive disabled flag shared with the touch tracker and the context.
const disabled = computed(() => props.disabled)

const { active, handlers } = useTouchActive(disabled)

// Only when the button is active and not disabled is the active style applied,
// matching `isEffectiveActive = active && !disabled` in React.
const isEffectiveActive = computed(() => active.value && !props.disabled)

// Equivalent to `clsx(className, { 'ui-active', 'ui-disabled' })` in React.
const rootClass = computed(() => [
  props.className,
  {
    'ui-active': isEffectiveActive.value,
    'ui-disabled': props.disabled,
  },
])

// Mirror `<ButtonContext.Provider value={{ active: isEffectiveActive, disabled }}>`.
provideButtonContext({ active: isEffectiveActive, disabled })

function handleTap() {
  if (props.disabled) return
  emit('click')
}
</script>

<template>
  <view
    :class="rootClass"
    :style="props.style"
    :event-through="false"
    v-bind="props.buttonProps"
    @tap="handleTap"
    @touchstart="handlers.touchstart"
    @touchend="handlers.touchend"
    @touchcancel="handlers.touchcancel"
  >
    <!--
      Default scoped slot mirrors React render-prop children. Plain children
      ignore the slot props; render-prop consumers read { active, disabled }.
    -->
    <slot :active="isEffectiveActive" :disabled="props.disabled" />
  </view>
</template>

// packages/lynx-ui-button/src/Button.tsx
// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

import { createContext, useContext, useMemo, useState } from '@lynx-js/react'

import { useMemoizedFn } from '@lynx-js/lynx-ui-common'
import { clsx } from 'clsx'

import type { ButtonProps } from './types'

export const ButtonContext = createContext<{
  active: boolean
  disabled: boolean
}>({
  active: false,
  disabled: false,
})

export const useButtonContext = () => useContext(ButtonContext)

export const Button = (prop: ButtonProps) => {
  const {
    children,
    onClick,
    disabled = false,
    style,
    className,
    buttonProps,
  } = prop
  const [active, setActive] = useState(false)

  // Only when the button is active and not disabled, the active style will be applied
  const isEffectiveActive = active && !disabled

  const renderedChildren = typeof children === 'function'
    ? children({ active: isEffectiveActive, disabled })
    : children

  const handleTouchStart = useMemoizedFn(() => {
    if (disabled) return
    setActive(true)
  })

  const handleTouchEnd = useMemoizedFn(() => {
    setActive(false)
    if (disabled) return
  })

  const handleTap = useMemoizedFn(() => {
    if (disabled) return
    onClick?.()
  })

  const contextValue = useMemo(
    () => ({ active: isEffectiveActive, disabled }),
    [isEffectiveActive, disabled],
  )

  return (
    <ButtonContext.Provider value={contextValue}>
      <view
        bindtap={handleTap}
        bindtouchstart={handleTouchStart}
        bindtouchend={handleTouchEnd}
        bindtouchcancel={handleTouchEnd}
        event-through={false}
        style={style}
        className={clsx(className, {
          'ui-active': isEffectiveActive,
          'ui-disabled': disabled,
        })}
        {...buttonProps}
      >
        {renderedChildren}
      </view>
    </ButtonContext.Provider>
  )
}
